### PR TITLE
[base] Add hb_ot_layout_get_baseline API

### LINKED ISSUE #418: support for 'hang' BASE OpenType feature
Please support the [BASE](https://www.microsoft.com/typography/otspec/baselinetags.htm) OpenType feature. I've gathered all information I was able to find on [a dedicated Github repo](https://github.com/eroux/otf-base-hang). There's a font with a hang BASE table in the [LO bug report](https://bugs.documentfoundation.org/show_bug.cgi?id=104930). Apparently recent MS Word support it, OSX apps don't, but they support the [AAT bsln](https://developer.apple.com/fonts/TrueType-Reference-Manual/RM06/Chap6bsln.html) table, which is more or less equivalent.

### PR DESCRIPTION
**Pull request by ebraminio**
Fixes #418
Closes #1354 (that one goes for `bsln` also which this one isn't, but this one has [a not finalized] simulation per the spec)

### CODE REVIEW

File: src/hb-ot-layout.cc [hunk 1]
```diff
@@ -1949,7 +1949,90 @@ hb_ot_layout_get_baseline (hb_font_t               *font,
 			   hb_tag_t                 language_tag,
 			   hb_position_t           *coord        /* OUT.  May be NULL. */)
 {
-  return font->face->table.BASE->get_baseline (font, baseline_tag, direction, script_tag, language_tag, coord);
+  hb_face_t *face = font->face;
+#define INVALID INT_MAX
+  *coord = INVALID;
```
Comment (ebraminio) [inline src/hb-ot-layout.cc]: Returning false when couldn't find the value inside the font and INT_MAX in the value when simulation has failed.

File: src/hb-ot-layout.cc [hunk 2]
```diff
@@ -1949,7 +1962,89 @@ hb_ot_layout_get_baseline (hb_font_t               *font,
...
+  bool is_horizontal = HB_DIRECTION_IS_HORIZONTAL (direction);
+  hb_position_t ideoEmboxBottom = INVALID, ideoEmboxLeft = INVALID, ideoEmboxTop = INVALID, ideoEmboxRight = INVALID;
+  hb_position_t icfBottom = INVALID, icfLeft = INVALID, icfTop = INVALID, icfRight = INVALID;
+  struct { hb_position_t ideo = INVALID, idtp = INVALID, icfb = INVALID, icft = INVALID; } HorizAxis, VertAxis;
+  hb_position_t margin = INVALID;
+#define GET_BASE(axis, member) font->face->table.BASE->get_baseline (font, member##_tag, \
+				&axis == &HorizAxis ? HB_DIRECTION_TTB : HB_DIRECTION_LTR, \
+				script_tag, language_tag, &axis.member)
+
+  /* https://docs.microsoft.com/en-us/typography/opentype/spec/baselinetags#ideographic-em-box */
```
Comment (ebraminio) [inline src/hb-ot-layout.cc]: Tried to mimic the specification with a DSL, still not sure if I've got it right as lack of indention on the pseudocode...

File: src/hb-ot-layout.cc [hunk 3]
```diff
@@ -1941,6 +1941,19 @@ hb_ot_layout_substitute_lookup (OT::hb_ot_apply_context_t *c,
...
+ * @font: a font
+ * @baseline: a baseline tag
+ * @direction: text direction.
+ * @script_tag:  script tag.
+ * @language_tag: language tag.
+ * @coord: (out): baseline value, INT_MAX when simulation also failed.
+ *
+ * Fetches a baseline value from the face, simulate if is possible.
+ *
+ * Return value: true only if the baseline is found inside the font.
```
Comment (ebraminio) [inline src/hb-ot-layout.cc]: Maybe we can return a tristate enum instead, enum { NONE, EXISTS, SIMULATED } or something.

File: src/hb-ot-layout.cc [hunk 4]
```diff
@@ -1949,7 +1962,89 @@ hb_ot_layout_get_baseline (hb_font_t               *font,
...
+  if (GET_BASE (VertAxis, idtp))
+    ideoEmboxRight = VertAxis.idtp;
+  else
+    ideoEmboxRight = upem;
+  if (GET_BASE (VertAxis, ideo) && VertAxis.ideo)
+  { /* Warning: Bad VertAxis.ideo value */ }
+  else /* If this is a CJK font: */ /* But we haven't implemented this check */
+  {
+    ideoEmboxBottom = font->face->table.OS2->sTypoDescender;
+    ideoEmboxTop = font->face->table.OS2->sTypoAscender;
```
Comment (ebraminio) [inline src/hb-ot-layout.cc]: I couldn't use the just introduced ot-metrics API as the it is needed to have the value unscaled till the end.

File: src/hb-ot-layout.cc (hunk 2 above)
Comment (dscorbett) [reply src/hb-ot-layout.cc]: [The old version of the page](http://web.archive.org/web/20170714012736/https://www.microsoft.com/typography/otspec/baselinetags.htm) has proper indentation.

Comment (ebraminio) [reply src/hb-ot-layout.cc]: Coool, thanks!

**Comment by ebraminio** [comment]
Please note that this API doesn't need language_tag but we are getting as the discussions (its min_max part needs however which is separate from this).

Maybe this should go in hb-ot-baseline instead hb-ot-layout so then we can expose min_max part also.

File: src/hb-ot-layout.h [hunk 5]
```diff
@@ -402,6 +402,38 @@ hb_ot_layout_feature_get_characters (hb_face_t      *face,
...
+ * Since: REPLACEME
+ */
+typedef enum {
+  HB_OT_LAYOUT_BASELINE_TIBETAN_HANGING					= HB_TAG('h','a','n','g'),
+  HB_OT_LAYOUT_BASELINE_IDEOGRAPHIC_CHARACTER_FACE_BOTTOM_OR_LEFT_EDGE	= HB_TAG('i','c','f','b'),
+  HB_OT_LAYOUT_BASELINE_IDEOGRAPHIC_CHARACTER_FACE_TOP_OR_RIGHT_EDGE	= HB_TAG('i','c','f','t'),
+  HB_OT_LAYOUT_BASELINE_IDEOGRAPHIC_EMBOX_BOTTOM_OR_LEFT_EDGE		= HB_TAG('i','d','e','o'),
+  HB_OT_LAYOUT_BASELINE_IDEOGRAPHIC_EMBOX_TOP_OR_RIGHT_EDGE		= HB_TAG('i','d','t','p'),
+  HB_OT_LAYOUT_BASELINE_MATHEMATICAL_CHARACTERS_CENTER			= HB_TAG('m','a','t','h'),
+  HB_OT_LAYOUT_BASELINE_ROMAN						= HB_TAG('r','o','m','n'),
```
Comment (ebraminio) [inline src/hb-ot-layout.h]: Something I've chosen, please review all of them and suggest better ones.

File: src/hb-ot-layout.cc [hunk 6]
```diff
@@ -1940,75 +1940,117 @@ hb_ot_layout_substitute_lookup (OT::hb_ot_apply_context_t *c,
...
-
-  /* TODO: Simulate https://docs.microsoft.com/en-us/typography/opentype/spec/baselinetags#ideographic-em-box */
-  if (!result && coord) *coord = 0;
+#define INVALID INT_MAX
+  *coord = INVALID;
+  bool result = font->face->table.BASE->get_baseline (font, baseline_tag, direction, script_tag, language_tag, coord);
+
+#define SCALE(value) (value != INVALID ? (HB_DIRECTION_IS_HORIZONTAL (direction) \
+					  ? font->em_scale_y (value) \
+					  : font->em_scale_x (value)) : value)
```
Comment (ebraminio) [inline src/hb-ot-layout.cc]: Do _y scale if the given script direction is horizontal and do _x scale if is vertical, matches what ot-metrics IIUC.

File: src/hb-ot-layout.h [hunk 7]
```diff
@@ -402,6 +402,38 @@ hb_ot_layout_feature_get_characters (hb_face_t      *face,
...
+ * Since: REPLACEME
+ */
+typedef enum {
+  HB_OT_LAYOUT_BASELINE_TIBETAN_HANGING					= HB_TAG ('h','a','n','g'),
+  HB_OT_LAYOUT_BASELINE_IDEOGRAPHIC_CHARACTER_FACE_BOTTOM_OR_LEFT_EDGE	= HB_TAG ('i','c','f','b'),
+  HB_OT_LAYOUT_BASELINE_IDEOGRAPHIC_CHARACTER_FACE_TOP_OR_RIGHT_EDGE	= HB_TAG ('i','c','f','t'),
+  HB_OT_LAYOUT_BASELINE_IDEOGRAPHIC_EMBOX_BOTTOM_OR_LEFT_EDGE		= HB_TAG ('i','d','e','o'),
+  HB_OT_LAYOUT_BASELINE_IDEOGRAPHIC_EMBOX_TOP_OR_RIGHT_EDGE		= HB_TAG ('i','d','t','p'),
+  HB_OT_LAYOUT_BASELINE_MATHEMATICAL_CHARACTERS_CENTER			= HB_TAG ('m','a','t','h'),
+  HB_OT_LAYOUT_BASELINE_ROMAN						= HB_TAG ('r','o','m','n'),
```
Comment (behdad) [inline src/hb-ot-layout.h]: need `_TAG` in value names.  They must match enum name.

File: src/hb-ot-layout.h [hunk 8]
```diff
@@ -402,6 +402,38 @@ hb_ot_layout_feature_get_characters (hb_face_t      *face,
...
+
+/**
+ * hb_ot_layout_baseline_tag_t:
+ *
+ * https://docs.microsoft.com/en-us/typography/opentype/spec/baselinetags
+ *
+ * Since: REPLACEME
+ */
+typedef enum {
+  HB_OT_LAYOUT_BASELINE_TIBETAN_HANGING					= HB_TAG ('h','a','n','g'),
```
Comment (behdad) [inline src/hb-ot-layout.h]: Remove TIBETAN.

File: src/hb-ot-layout.h [hunk 9]
```diff
@@ -402,6 +402,38 @@ hb_ot_layout_feature_get_characters (hb_face_t      *face,
...
+  HB_OT_LAYOUT_BASELINE_IDEOGRAPHIC_CHARACTER_FACE_BOTTOM_OR_LEFT_EDGE	= HB_TAG ('i','c','f','b'),
+  HB_OT_LAYOUT_BASELINE_IDEOGRAPHIC_CHARACTER_FACE_TOP_OR_RIGHT_EDGE	= HB_TAG ('i','c','f','t'),
+  HB_OT_LAYOUT_BASELINE_IDEOGRAPHIC_EMBOX_BOTTOM_OR_LEFT_EDGE		= HB_TAG ('i','d','e','o'),
+  HB_OT_LAYOUT_BASELINE_IDEOGRAPHIC_EMBOX_TOP_OR_RIGHT_EDGE		= HB_TAG ('i','d','t','p'),
+  HB_OT_LAYOUT_BASELINE_MATHEMATICAL_CHARACTERS_CENTER			= HB_TAG ('m','a','t','h'),
```
Comment (behdad) [inline src/hb-ot-layout.h]: Just `MATH`.

File: src/hb-ot-layout.h [hunk 10]
```diff
@@ -402,6 +402,38 @@ hb_ot_layout_feature_get_characters (hb_face_t      *face,
...
+ * https://docs.microsoft.com/en-us/typography/opentype/spec/baselinetags
+ *
+ * Since: REPLACEME
+ */
+typedef enum {
+  HB_OT_LAYOUT_BASELINE_TIBETAN_HANGING					= HB_TAG ('h','a','n','g'),
+  HB_OT_LAYOUT_BASELINE_IDEOGRAPHIC_CHARACTER_FACE_BOTTOM_OR_LEFT_EDGE	= HB_TAG ('i','c','f','b'),
+  HB_OT_LAYOUT_BASELINE_IDEOGRAPHIC_CHARACTER_FACE_TOP_OR_RIGHT_EDGE	= HB_TAG ('i','c','f','t'),
+  HB_OT_LAYOUT_BASELINE_IDEOGRAPHIC_EMBOX_BOTTOM_OR_LEFT_EDGE		= HB_TAG ('i','d','e','o'),
+  HB_OT_LAYOUT_BASELINE_IDEOGRAPHIC_EMBOX_TOP_OR_RIGHT_EDGE		= HB_TAG ('i','d','t','p'),
```
Comment (behdad) [inline src/hb-ot-layout.h]: `IDEOGRAPHIC` -> `IDEO`.  Remove `_CHARACTER`.  Remove `_EDGE`.

File: src/hb-ot-layout-base-table.hh [hunk 11]
```diff
@@ -376,10 +373,10 @@ struct BaseScriptList
 
 struct Axis
 {
-  bool get_baseline (hb_ot_layout_baseline_t   baseline,
-		     hb_tag_t                  script_tag,
-		     hb_tag_t                  language_tag,
-		     const BaseCoord         **coord) const
+  bool get_baseline (hb_ot_layout_baseline_tag_t   baseline,
```
Comment (behdad) [inline src/hb-ot-layout-base-table.hh]: Just take `hb_tag_t` here.  The type comes in just in public API.

File: src/hb-ot-layout.cc [hunk 12]
```diff
@@ -1940,75 +1940,117 @@ hb_ot_layout_substitute_lookup (OT::hb_ot_apply_context_t *c,
...
+			   hb_position_t               *coord        /* OUT.  May be NULL. */)
 {
-  bool result = font->face->table.BASE->get_baseline (font, baseline, direction, script_tag,
-						      language_tag, coord);
-
-  /* TODO: Simulate https://docs.microsoft.com/en-us/typography/opentype/spec/baselinetags#ideographic-em-box */
-  if (!result && coord) *coord = 0;
+#define INVALID INT_MAX
+  *coord = INVALID;
+  bool result = font->face->table.BASE->get_baseline (font, baseline_tag, direction, script_tag, language_tag, coord);
```
Comment (behdad) [inline src/hb-ot-layout.cc]: You shouldn't write to `coord` until we find.

Comment (behdad) [reply src/hb-ot-layout.cc]: Ugh.  I hate this function.

Remove all the simulation.  Let's get a simple fetcher implementation in first.  Then we talk about simulation if needed.

File: src/hb-ot-layout.cc (hunk 3 above)
Comment (behdad) [reply src/hb-ot-layout.cc]: No need for tristate.  If needed, is fine to "return false and output simulated".  We do that in some other API.

File: src/hb-ot-layout.h (hunk 7 above)
Comment (ebraminio) [reply src/hb-ot-layout.h]: So hb-ot-meta and hb-ot-metrics enums also?

**Comment by ebraminio** [comment]
> Please push the noncontroversial parts into master and create/update PR for the parts that need discussion. I'm highly suspicious of needing to simulate stuff the way spec specifies. So, I like to stare at that separately and discuss it in a separate PR.

Do you see any noncontroversial part in this? I don't :) Was nice if GitHub had Gerrit like dependent changes

File: src/hb-ot-layout.cc (hunk 4 above)
Comment (behdad) [reply src/hb-ot-layout.cc]: Umm. Need to apply the sign conversion.  Plus, variations.  I think you have to use the metrics API.  Again, remove the fallback and we rebuild it separately.

File: src/hb-ot-layout.h (hunk 7 above)
Comment (behdad) [reply src/hb-ot-layout.h]: Yes.  Enums always have to be consistent like that.

File: src/hb-ot-layout.cc (hunk 4 above)
Comment (ebraminio) [reply src/hb-ot-layout.cc]: Removed simulation and put it here for future reference https://github.com/harfbuzz/harfbuzz/compare/master...ebraminio:baseline-base

**Comment by ebraminio** [comment]
All done, let me know if you like hb-ot-baseline more instead hb-ot-layout.

File: src/hb-ot-layout.h [hunk 13]
```diff
@@ -402,6 +402,38 @@ hb_ot_layout_feature_get_characters (hb_face_t      *face,
...
+ * Since: REPLACEME
+ */
+typedef enum {
+  HB_OT_LAYOUT_BASELINE_TAG_HANGING			= HB_TAG ('h','a','n','g'),
+  HB_OT_LAYOUT_BASELINE_TAG_IDEO_FACE_BOTTOM_OR_LEFT	= HB_TAG ('i','c','f','b'),
+  HB_OT_LAYOUT_BASELINE_TAG_IDEO_FACE_TOP_OR_RIGHT	= HB_TAG ('i','c','f','t'),
+  HB_OT_LAYOUT_BASELINE_TAG_IDEO_EMBOX_BOTTOM_OR_LEFT	= HB_TAG ('i','d','e','o'),
+  HB_OT_LAYOUT_BASELINE_TAG_IDEO_EMBOX_TOP_OR_RIGHT	= HB_TAG ('i','d','t','p'),
+  HB_OT_LAYOUT_BASELINE_TAG_MATH			= HB_TAG ('m','a','t','h'),
+  HB_OT_LAYOUT_BASELINE_TAG_ROMAN			= HB_TAG ('r','o','m','n'),
```
Comment (behdad) [inline src/hb-ot-layout.h]: Move ROMAN to be first, since it's the most common...

**Comment by behdad** [comment]
Looks great.  Don't forget adding to docs.  Merge after that minor issue.
