### PR TITLE
Fix reading fonts from stdin

### LINKED ISSUE #1001: hb-{view,shape} should support reading font file from stdin
It should both support, `hb-{shape,view} {/dev/stdin,-} <font.ttf` and `cat font.ttf | hb-{shape,view} {/dev/stdin,-}`. More nice if it uses `hb_blob_create_from_file` underneath. It should be tested on both Linux and macOS (their implementation differs), and even better, Windows also (\r thing). AIX doesn't have `/dev/stdin` (not the most used platform, but well) so we should have some workaround for that in mind also (specially not redirecting `-` to `/dev/stdin`)

### PR DESCRIPTION
**Pull request by ebraminio**
Fixes #1001 

We were passing the font path directly to freetype so rendering
was broken when we are getting the font from stdin.

This fixes it by using FT_New_Memory_Face instead.

This fixes:
* build/util/hb-view /dev/stdin text < font.ttf
* build/util/hb-view - text < font.ttf
* cat font.ttf | build/util/hb-view - text

but this doesn't work on
* cat font.ttf | build/util/hb-view /dev/stdin text

Which I will try to fix separately.

### CODE REVIEW

File: util/helper-cairo.cc [hunk 1]
```diff
@@ -89,10 +89,16 @@ helper_cairo_create_scaled_font (const font_options_t *font_opts)
       atexit (free_ft_library);
 #endif
     }
-    FT_New_Face (ft_library,
-		 font_opts->font_file,
-		 font_opts->face_index,
-		 &ft_face);
+
+    unsigned int blob_length;
+    const char *blob_data = hb_blob_get_data (font_opts->blob, &blob_length);
```
Comment (ebraminio) [inline util/helper-cairo.cc]: We shouldn't have pass file path directly to the freetype, that was causing shaping with one font and rendering with another, the weirdness you were describing Behdad.

File: util/options.cc [hunk 2]
```diff
@@ -663,8 +661,9 @@ font_options_t::get_font (void) const
 	      strerror (errno));
       g_string_append_len (gs, buf, ret);
     }
+    unsigned int len = gs->len;
     char *font_data = g_string_free (gs, false);
-    blob = hb_blob_create (font_data, gs->len,
```
Comment (ebraminio) [inline util/options.cc]: My fault, as it was broken, I didn't notice I broke it even more.

File: util/options.hh [hunk 3]
```diff
@@ -471,6 +472,7 @@ struct font_options_t : option_group_t
   hb_font_t *get_font (void) const;
 
   char *font_file;
+  mutable hb_blob_t *blob;
```
Comment (ebraminio) [inline util/options.hh]: Have a look if is needed.

File: util/options.hh [hunk 4]
```diff
@@ -483,7 +485,7 @@ struct font_options_t : option_group_t
   mutable double font_size_y;
   char *font_funcs;
 
-  private:
+private:
```
Comment (behdad) [inline util/options.hh]: We keep private:, etc, indented.

File: util/helper-cairo.cc (hunk 1 above)
Comment (behdad) [reply util/helper-cairo.cc]: Right. Thanks.
