### PR TITLE
[syllabic] Set position of dotted circle for Indic

### LINKED ISSUE #2997: Clusters level 1 not monotone with FreeSans.
With HarfBuzz 243d056ff1c2af583ceb67e5dfbfaac51dc96e63 from June 2nd, 2021 (current tip of tree)

```
~/src/harfbuzz$ meson build
harfbuzz 2.8.1

  Directories
               prefix: /usr/local
               bindir: bin
               libdir: lib/x86_64-linux-gnu
           includedir: include
              datadir: share

  Unicode callbacks (you want at least one)
              Builtin: YES
                 Glib: YES
                  ICU: YES

  Font callbacks (the more the merrier)
             FreeType: YES

  Dependencies used for command-line utilities
                Cairo: YES
                Chafa: NO

  Additional shapers
            Graphite2: NO

  Platform shapers (not normally needed)
             CoreText: NO
          DirectWrite: NO
        GDI/Uniscribe: NO

  Other features
        Documentation: YES
     GObject bindings: YES
        Introspection: NO
    Experimental APIs: NO

  Testing
                Tests: YES
            Benchmark: NO

~/src/harfbuzz$ ninja -C build/

~/src/harfbuzz$ build/util/hb-shape --verify --cluster-level=1 --unicodes="d4e 200c d4d 200d" /usr/share/fonts/truetype/freefont/FreeSans.ttf
error: clusters are not monotone.
[dottedcircle=0+800|space=1+0|candrakala=2+0|space=3+0|reph_mal=0+273]
```

This is with FreeSans.ttf with SHA-1 of bca12eb97225af6c1587ca4f53ed9bf9f8fd7614 , currently available from Debian. Attaching this font as [FreeSans.gz](https://github.com/harfbuzz/harfbuzz/files/6587479/FreeSans.gz) (gziped, since cannot attach without zipping) since it claims GPLv3 with document exception.

### PR DESCRIPTION
**Pull request by dscorbett**
Fixes #2997.

### CODE REVIEW

File: src/hb-ot-shape-complex-syllabic.hh [hunk 1]
```diff
@@ -35,7 +35,8 @@ hb_syllabic_insert_dotted_circles (hb_font_t *font,
 				   hb_buffer_t *buffer,
 				   unsigned int broken_syllable_type,
 				   unsigned int dottedcircle_category,
-				   int repha_category = -1);
+				   int repha_category = -1,
+				   unsigned int dottedcircle_position = -1);
```
Comment (behdad) [inline src/hb-ot-shape-complex-syllabic.hh:39]: Ah, since we are doing conditional assignment for `repha_category`, let's do the same for `dottedcircle_position`. Make it `int` and only use if not `-1`.

Can you also add a test please? Thanks!
