### PR TITLE
[circleci] Fix "msan" and "everything" bots

### LINKED ISSUE #1203: fix clang-everything bot
Interestingly "clang-everything" fails consistently due to an unrelated reason, maybe because of -fPIC I've put on there or some other parts of my change https://github.com/harfbuzz/harfbuzz/commit/0fa1edb (which was working smoothly before it)

https://circleci.com/gh/harfbuzz/harfbuzz/35657

```
FAIL tests/HVAR-1.tests (exit status: 1)
==== ./test/shaping/data/text-rendering-tests/tests/GVAR-7.log ====
Running tests in ./tests/GVAR-7.tests
../../../../util/hb-shape fonts/TestGVARFour.ttf --verify --font-size=1000 --ned --remove-default-ignorables --font-funcs=ft --variations=wght=150 --unicodes U+004F,U+0049,U+004F


Actual:   [uni004F|uni0049@700,0|uni004F@1095,0]
Expected: [uni004F|uni0049@706,0|uni004F@1072,0]
```

Rings any bell?

### LINKED ISSUE #1204: [msan] Use newer glib
From hb-glib.h:
```
#if GLIB_CHECK_VERSION(2,31,10) 
HB_EXTERN hb_blob_t * 
hb_glib_blob_create (GBytes *gbytes); 
#endif 
```

We install 2.28...  Why so old?  Just use newer and it should fix the check-symbols.sh failure.  You should then revert your hack.  Thanks.

### PR DESCRIPTION
**Pull request by ebraminio**
Fixes #1204 
Fixes #1203

### CODE REVIEW

File: test/fuzzing/hb-fuzzer.hh [hunk 1]
```diff
@@ -1,4 +1,4 @@
 #include <hb.h>
 #include <stddef.h>
 
-extern "C" int LLVMFuzzerTestOneInput(const uint8_t *data, size_t size);
```
Comment (behdad) [inline test/fuzzing/hb-fuzzer.hh]: Please don't change the signature here.  It must match what libFuzzer expects.  Add a cast to main.cc.
