### PR TITLE
Fix -Wsizeof-array-div clang warning

### LINKED ISSUE #1969: Clang warning of type -Wsizeof-array-div for arabic fallback shaping static assert
See https://bugs.chromium.org/p/chromium/issues/detail?id=1002945#c5

```
[1993/73487] CXX win_clang_nacl_win64/obj/third_party/harfbuzz-ng/harfbuzz_source/hb-ot-shape-complex-arabic.obj
In file included from ../../third_party/harfbuzz-ng/src/src/hb-ot-shape-complex-arabic.cc:245:
../../third_party/harfbuzz-ng/src/src/hb-ot-shape-complex-arabic-fallback.hh(233,68): warning: expression does not compute the number of elements in this array; element type is 'const unsigned char', not 'ManifestLookup' [-Wsizeof-array-div]
  static_assert (sizeof (arabic_win1256_gsub_lookups.manifestData) / sizeof ()
                         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~  ^
1 warning generated.
```

From a cursory inspection, this looks like it could be a true positive.

MANIFEST starts with OT_LABEL_START which places a
`unsigned char Name[`

whereas `ManifestLookup` is a Tag + Offset struct.

### PR DESCRIPTION
**Pull request by ebraminio**
Fixes #1969

### CODE REVIEW

File: src/hb-ot-shape-complex-arabic-fallback.hh [hunk 1]
```diff
@@ -230,8 +230,8 @@ arabic_fallback_plan_init_win1256 (arabic_fallback_plan_t *fallback_plan HB_UNUS
     return false;
 
   const Manifest &manifest = reinterpret_cast<const Manifest&> (arabic_win1256_gsub_lookups.manifest);
-  static_assert (sizeof (arabic_win1256_gsub_lookups.manifestData) / sizeof (ManifestLookup)
-		 <= ARABIC_FALLBACK_MAX_LOOKUPS, "");
+  static_assert (sizeof (arabic_win1256_gsub_lookups.manifestData) ==
+		 ARABIC_FALLBACK_MAX_LOOKUPS * sizeof (ManifestLookup), "");
```
Comment (drott) [inline src/hb-ot-shape-complex-arabic-fallback.hh]: Good idea!
